# Generated by Django 5.0.3 on 2024-05-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_name', models.CharField(max_length=50)),
                ('about_the_news', models.TextField(max_length=500)),
                ('release_date', models.DateField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oynanan_oyun', models.IntegerField(max_length=50)),
                ('qalibiyet', models.IntegerField(max_length=50)),
                ('meglubiyet', models.IntegerField(max_length=50)),
                ('total', models.IntegerField(max_length=50)),
            ],
        ),
    ]
